version: "3.8"

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node_env
    tty: true
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./:/home/alex/aoc
    working_dir: /home/alex/aoc